name: Columbina
description: "I'm Columbina, a multi-purpose Discord bot that provides a variety of\
  \ features with my aesthetic to enhance your server experience. \nOn the other hand,\
  \ i am also made for people who play genshin."
version: 1.4.2
developer:
  username: chromavisionmusic
  user_id: '1063860912173359114'
author:
  username: hanakitty3
  user_id: '758254880770490378'
bot_id: '1407769283148251248'
server:
  invite: https://discord.gg/Zupa7pqJK8
prefix:
- 'bina '
- 'Bina '
- 'BINA '
chatbot_channel_ids:
- '1337477436643868694'
- '1337174889571942430'
- '1409271241176780902'
colors:
  primary:
  - 130
  - 71
  - 126
  secondary:
  - 136
  - 147
  - 213
  info:
  - 170
  - 170
  - 170
  warning:
  - 240
  - 173
  - 78
  success:
  - 34
  - 187
  - 51
  error:
  - 187
  - 33
  - 36
activity:
  name: Song of the Welkin Moon
  type: listening
logging:
  level: ERROR
  file: logs/discord.log
