version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: columbina-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - columbina-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  columbina:
    build: .
    container_name: columbina-bot
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./logs:/app/logs
    networks:
      - columbina-network

networks:
  columbina-network:
    driver: bridge

volumes:
  redis_data:
