name: Version Bump

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'fix') || 
      contains(github.event.head_commit.message, 'feat')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install bump dependencies
        run: pip install toml pyyaml

      - name: Bump version in pyproject.toml and config.yaml
        id: bump
        run: |
          python scripts/bump.py "${{ github.event.head_commit.message }}"

      - name: Commit bumped version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml config.yaml
          git commit -m "chore: bump version to ${{ steps.bump.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
